name: 'Unity Build Pipeline Utility'
description: 'Runs a Unity build action using the specified arguments'
branding:
  icon: 'box'
  color: 'blue'

inputs:
  build-target:
    description: 'The build target to build for.'
    # Unity -buildTarget command line args https://docs.unity3d.com/Manual/CommandLineArguments.html
    # StandaloneWindows64, WSAPlayer, StandaloneOSX, iOS, StandaloneLinux64, Android, Lumin, WebGL
    default: ''
  test:
    description: 'Run editor tests'
    required: false
    default: 'true'
  additional-validation-args:
    description: 'Additional args to pass to validation command'
    required: false
    default: ''
  additional-test-args:
    description: 'Additional args to pass to test command'
    required: false
    default: ''
  additional-build-args:
    description: 'Additional args to pass to build command'
    required: false
    default: ''
  output-directory:
    description: 'The directory to output the build to'
    required: false
    default: ''
  publish-artifacts:
    description: 'Should the workflow publish artifacts?'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - run: |
        echo "::group::Running Unity Build Pipeline Utility"

        $outputDirectoryArgs = ''
        $outputDirectory = '${{ env.UNITY_PROJECT_PATH }}/Builds'

        if ("${{ inputs.output-directory }}" -ne "") {
          $outputDirectoryArgs = ' -buildOutputDirectory ${{ inputs.output-directory }}'
          $outputDirectory = '${{ inputs.output-directory }}'
        }

        echo "OutputDirectory: $outputDirectory"
        echo "OutputDirectoryArgs: $outputDirectoryArgs"

        "OUTPUT_DIRECTORY=$outputDirectory" >> $env:GITHUB_ENV
        "OUTPUT_DIRECTORY_ARGS=$outputDirectoryArgs" >> $env:GITHUB_ENV
      shell: pwsh

    - uses: xrtk/unity-action@v6
      name: Project Validation
      with:
        log-name: 'project-validation'
        args: '-quit -nographics -batchmode -executeMethod Utilities.Editor.BuildPipeline.UnityPlayerBuildTools.ValidateProject ${{ inputs.additional-validation-args }}'

    - uses: xrtk/unity-action@v6
      if: ${{ inputs.test == 'true' }}
      name: '${{ inputs.build-target }}-Tests'
      with:
        log-name: '${{ inputs.build-target }}-Tests'
        build-target: '${{ inputs.build-target }}'
        args: '-nographics -batchmode -runEditorTests ${{ inputs.additional-test-args }}'

    - uses: xrtk/unity-action@v6
      name: '${{ inputs.build-target }}-Build'
      with:
        log-name: '${{ inputs.build-target }}-Build'
        build-target: '${{ inputs.build-target }}'
        args: >-
          -quit -nographics -batchmode -executeMethod Utilities.Editor.BuildPipeline.UnityPlayerBuildTools.StartCommandLineBuild ${{ inputs.additional-build-args }}${{ env.OUTPUT_DIRECTORY_ARGS }}

    - name: Ensure Unity process is dead
      if: always()
      run: |
        $processIdFile = Join-Path $env:GITHUB_WORKSPACE "unity-process-id.txt"

        if (Test-Path $processIdFile) {
          $processId = Get-Content $processIdFile
          Write-Host "::debug::Unity Process ID found: $processId"
          $unityProcess = Get-Process -Id $processId -ErrorAction SilentlyContinue
          if ($unityProcess -and !$unityProcess.HasExited) {
            Write-Host "::debug::Killing Unity process with PID $processId"
            Stop-Process -Id $processId -Force
          }
        }
      shell: pwsh

    - uses: actions/upload-artifact@v4
      name: Upload Artifacts
      if: ${{ always() && inputs.publish-artifacts == 'true' }}
      with:
        overwrite: true
        retention-days: 1
        compression-level: 0
        name: '${{ github.run_number }}.${{ github.run_attempt }}-${{ runner.os }}-${{ inputs.build-target }}-Artifacts'
        path: |
          ${{ env.UNITY_PROJECT_PATH }}/Logs/*.log
          ${{ env.OUTPUT_DIRECTORY }}/**/*

    - name: Clean Artifacts
      if: ${{ always() && inputs.publish-artifacts == 'true' }}
      run: |
        # Clean Logs
        Get-ChildItem -Path "${{ env.UNITY_PROJECT_PATH }}" -File -Filter "*.log" -Recurse | ForEach-Object { Write-Host "::debug:: $_" }
        Get-ChildItem -Path "${{ env.UNITY_PROJECT_PATH }}" -File -Filter "*.log" -Recurse | Remove-Item -Force

        # Clean Artifacts
        $artifacts = "${{ env.OUTPUT_DIRECTORY }}"
        Write-Host "::debug::Build artifacts path: $artifacts"

        if (Test-Path -Path $artifacts) {
          Get-ChildItem -Path $artifacts -Recurse | ForEach-Object { Write-Host "::debug:: $_" }

          try {
            Remove-Item $artifacts -Recurse -Force
          } catch {
            Write-Warning "Failed to delete artifacts folder file: $_"
          }
        } else {
          Write-Host "::debug::Artifacts folder not found."
        }
      shell: pwsh

    - run: echo "::endgroup::"
      shell: pwsh
